docs: add git submodule handling documentation
alirezanet/Husky.Net pull request #82
Opened 2023-08-20 18:05 UTC by Tychus

Documentation for [PR:81](https://github.com/alirezanet/Husky.Net/pull/81)

2023-08-20 20:00 UTC, alirezanet requested changes

2023-08-20 20:00 UTC, alirezanet commented on docs/guide/getting-started.md
> +## Husky and git submodules
I think `submodule` related docs don't belong to the `getting-started` page since it might confuse the new users. It would be nice if you move it to a separate menu/file.

2023-08-21 18:17 UTC, Tychus commented on docs/guide/getting-started.md
> +## Husky and git submodules
good point i'll see what i can do

2023-08-21 18:35 UTC, Tychus commented on docs/guide/getting-started.md
> +## Husky and git submodules
@alirezanet  i'm having some issues running the doc locally, running the commands below starts VuePress and all but when i open any link it's a blank page. 

```
npm install
npm run dev
```

2023-08-22 15:32 UTC, alirezanet commented on docs/guide/getting-started.md
> +## Husky and git submodules
It is probably because I was using the beta version of vuepress ... I'll look into this later if you couldn't fix it. 👌

2023-08-26 11:13 UTC, alirezanet commented on docs/guide/getting-started.md
> +## Husky and git submodules
Hi @Tychus,

I solved the problem, you're able to run the docs locally now. 
just remove the `node_modules` folder before running it.

2023-08-26 14:39 UTC, Tychus commented on docs/guide/getting-started.md
> +## Husky and git submodules
Hope this is clear enough.

2023-08-26 14:42 UTC, alirezanet approved these changes
Awesome, 🚀💐

2023-08-26 14:42 UTC, merged